Repository openlawlibrary/pygls, pull requests merged in 2018-12, with the labels that each got.

#36 Add Implementations.md
  Implementations.md
  README.md
Labels: docs

#37 Improve readme
  README.md
  assets/img/readme/completion-list.png
  docs/source/index.rst
  setup.py
Labels: docs, enhancement

#38 Add pronunciation for pygls and fix typos
  README.md
Labels: docs

#40 release 0.7.1
  CHANGELOG.md
  docs/source/index.rst
  docs/source/pages/advanced_usage.rst
  docs/source/pages/tutorial.rst
  examples/README.md
  examples/json-extension/client/package-lock.json
  examples/json-extension/client/package.json
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
  examples/json-extension/server/server.py
  examples/json-extension/server/tests/unit/test_features.py
  pygls/server.py
  setup.py
Labels: bug, docs, enhancement

#41 Release 0.7.2
  CHANGELOG.md
  README.md
  examples/json-extension/client/package-lock.json
  examples/json-extension/client/package.json
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
  setup.py
Labels: bug, docs, release
