Repository openlawlibrary/pygls, pull requests merged in 2019-03, with the labels that each got.

#51 Bugfix open workspace assumption
  CHANGELOG.md
  CONTRIBUTORS.md
  pygls/exceptions.py
  pygls/protocol.py
  pygls/workspace.py
  tests/conftest.py
  tests/test_workspace.py
Labels: bug

#54 Add PR template
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
Labels: docs

#53 Update dependencies
  CHANGELOG.md
  appveyor.yml
  examples/json-extension/client/package-lock.json
  examples/json-extension/client/package.json
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
  setup.py
Labels: refactor

#55 Release v0.7.4
  CHANGELOG.md
  examples/json-extension/client/package-lock.json
  examples/json-extension/client/package.json
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
  setup.py
Labels: release

#56 Fix handling notification/request parameters that is not used for class fields name from the server
  CHANGELOG.md
  CONTRIBUTORS.md
  pygls/protocol.py
  tests/test_protocol.py
Labels: bug

#61 Add more tests for deserialize_message function
  CHANGELOG.md
  tests/test_protocol.py
Labels: enhancement
