Repository openlawlibrary/pygls, pull requests merged in 2019-01, with the labels that each got.

#43 Add `CONTRIBUTORS.md`; start using "Keep a Changelog" format.
  CHANGELOG.md
  CONTRIBUTORS.md
Labels: docs

#44 Fix AttributeError in _handle_notification method
  pygls/protocol.py
Labels: bug

#45 Fix passing custom protocol to language server + tests
  pygls/server.py
  tests/test_language_server.py
Labels: bug

#42 Fix possibly non existing parameter
  CONTRIBUTORS.md
  pygls/protocol.py
  pygls/types.py
  tests/test_language_server.py
Labels: bug

#47 Refactor LSP initialize method
  CHANGELOG.md
  appveyor.yml
  examples/json-extension/client/package-lock.json
  examples/json-extension/client/package.json
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
  pygls/exceptions.py
  pygls/protocol.py
  pygls/server.py
  pygls/types.py
  pygls/uris.py
  pygls/workspace.py
  setup.cfg
  setup.py
  tests/test_language_server.py
  tests/test_protocol.py
Labels: bug, devops
