Repository openlawlibrary/pygls, pull requests merged in 2020-04, with the labels that each got.

#105 Add InsertTextFormat enum
  .gitignore
  pygls/types.py
Labels: bug

#106 Update json-example npm packages
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
Labels: enhancement

#107 Updated SymbolKinds
  pygls/types.py
Labels: enhancement

#110 Release v0.9.0
  CHANGELOG.md
  examples/json-extension/package-lock.json
  examples/json-extension/package.json
  setup.py
Labels: release

#111 Add anakin-language-server to Implementations.md
  Implementations.md
Labels: docs
